sequence_length: 256
num_layers: 30

mask_config:
  mask_type: "causal"
  window_size: null
attention_config:
  num_heads: 32
  alibi_slopes: [[0.8408964152537145, 0.7071067811865476, 0.5946035575013605, 0.5, 0.42044820762685725, 0.3535533905932738, 0.29730177875068026, 0.25, 0.21022410381342863, 0.1767766952966369, 0.14865088937534013, 0.125, 0.10511205190671431, 0.08838834764831845, 0.07432544468767006, 0.0625, 0.052556025953357156, 0.04419417382415922, 0.03716272234383503, 0.03125, 0.026278012976678578, 0.02209708691207961, 0.018581361171917516, 0.015625, 0.013139006488339289, 0.011048543456039806, 0.009290680585958758, 0.0078125, 0.0065695032441696445, 0.005524271728019903, 0.004645340292979379, 0.00390625]]
  head_weights: null
  softmax_temperature: 1.0
content_config:
  diagonal_scores: [[-0.4914]]
  base_scores: [[9.8740]]
lambda_schedule_config:
  schedule_type: "custom"
  lambdas_custom: [0.23837663765251638,0.19156795774400234,0.24242439979314803,0.16082377901673317,0.12020408837497235,0.11336044000089168,0.11874557603150607,0.10117596762627364,0.09476314572244883,0.09072203657776118,0.09205478532612324,0.09298003394901752,0.08819286651164293,0.09760695550590753,0.09413643883168697,0.09252473046630622,0.10018595698475838,0.10231736520677805,0.10590481188893318,0.0982556182667613,0.10227319779247046,0.10199885623157025,0.09798091331869364,0.10664581298083067,0.11518675550818443,0.12017341221868992,0.13243172135204076,0.1758726865798235,0.13202865192294122,0.10044208954274654]

save_dir: ./results/rollout/mean_content/fineweb-edu/bloom-7b1/
