num_batches: 1000
batch_size: 1

save_path: /data/shared_data/position-bias/results-final-fineweb-edu

sequence_length: 1024

hf_model_config:
  model_id: anas-awadalla/mpt-7b
  cache_dir: /data/shared_data/position-bias/cache

dataset_config:
  dataset_name: fineweb-edu

wandb_config:
  project: position-bias
  dir: ./wandb/mpt-7b-1024
  name: mpt-7b-1024
  notes: Experiment 1 on MPT-7B model using FineWeb-Edu dataset.
  tags: [mpt-7b, alibi]
  group: alibi
  job_type: evaluating

enable_attention_stats: true
enable_attribution: true
enable_qk_stats: true
