num_batches: 1000
batch_size: 1

save_path: /data/shared_data/position-bias/results-final-fineweb-edu

sequence_length: 256

hf_model_config:
  model_id: eluzhnica/mpt-30b-peft-compatible
  cache_dir: /data/shared_data/position-bias/cache

dataset_config:
  dataset_name: fineweb-edu

wandb_config:
  project: position-bias
  dir: ./wandb/mpt-30b-256
  name: mpt-30b-256
  notes: Experiment 1 on MPT-30B model using FineWeb-Edu dataset.
  tags: [mpt-30b, alibi]
  group: alibi
  job_type: evaluating

enable_attention_stats: true
enable_attribution: true
enable_qk_stats: true
